spring:
  application:
    name: assessment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ims

server:
  port: 9004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
